mainapp/urls.py
from django.urls import path
from django.http import HttpRequest
from mainapp.views import (
    home,
    about,
    journal_detail_view,
    JournalListView,
    JournalDeleteView,
    JournalCreateView,
    JournalUpdateView,
    series_create_view,
    series_detail_view,
    SeriesUpdateView,
    SeriesDeleteView,
    issue_create_view,
    issue_detail_view,
    IssueUpdateView,
    IssueDeleteView,
    article_detail_view,
    article_list_view,
    article_create_view,
    ArticleUpdateView,
    ArticleDeleteView
)

app_name = 'main'

urlpatterns = [
    path('', JournalListView.as_view(), name='home'),
    # path('', home, name='home'),
    path('about/', about, name='about'),
    path('journal/<int:pk>/', journal_detail_view, name='journal-detail'),
    path('journal/<int:pk>/delete/', JournalDeleteView.as_view(), name='journal-delete'),
    path('journal/new/', JournalCreateView.as_view(), name='journal-create'),
    path('journal/<int:pk>/update/', JournalUpdateView.as_view(), name='journal-update'),

    path('series/<int:pk>/new/', series_create_view, name='series-create'),
    path('series/<int:pk>/', series_detail_view, name='series-detail'),
    path('series/<int:pk>/update/', SeriesUpdateView.as_view(), name='series-update'),
    path('series/<int:pk>/delete/', SeriesDeleteView.as_view(), name='series-delete'),

    path('issue/<int:pk>/new/', issue_create_view, name='issue-create'),
    path('issue/<int:pk>/', issue_detail_view, name='issue-detail'),
    path('issue/<int:pk>/update/', IssueUpdateView.as_view(), name='issue-update'),
    path('issue/<int:pk>/delete/', IssueDeleteView.as_view(), name='issue-delete'),

    path('articles/', article_list_view, name='article-list'),
    path('article/<int:pk>/', article_detail_view, name='article-detail'),
    path('article/new/', article_create_view, name='article-create'),
    path('article/new/<int:pk>/', article_create_view, name='article-issue-create'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article-update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article-delete'),
]

sci_journal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as user_views
from authapp import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'), name='main'),
    path('register/', auth_views.register, name='register'),
    path('profile/', auth_views.profile, name='profile'),
    path('login/', user_views.LoginView.as_view(template_name='authapp/login.html'), name='login'),
    path('logout/', user_views.LogoutView.as_view(template_name='authapp/logout.html'), name='logout'),
    path('password-reset/', user_views.PasswordResetView.as_view(template_name='authapp/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', user_views.PasswordResetDoneView.as_view
    (template_name='authapp/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', user_views.PasswordResetConfirmView.as_view
    (template_name='authapp/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/', user_views.PasswordResetCompleteView.as_view(template_name='authapp/password_reset_complete.html') 
        ,name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Journal(models.Model):
    name = models.CharField(verbose_name='Наименование журнала', max_length=128)
    issn = models.CharField(verbose_name='ISSN', max_length=64, blank=True)
    description = models.TextField(verbose_name='О журнале', blank=True)
    rkn_certificate_scan = models.FileField(verbose_name='Сканы сертификатов', upload_to='uploads/%Y/%m/%d/', blank=True)
    redactor = models.CharField(verbose_name='Редактор', max_length=128, blank=True)
    issue_period = models.CharField(verbose_name='Периодисность издания', max_length=32, blank=True)
    issuer = models.CharField(verbose_name='Издатель', max_length=64, blank=True)
    email = models.EmailField(verbose_name='Электронная почта', max_length=96, blank=True)
    phone = models.CharField(verbose_name='Телефон', max_length=64, blank=True)
    address = models.TextField(verbose_name='Почтовый адрес', blank=True)
    objects = models.Manager()
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:journal-detail', kwargs={'pk': self.pk})

    def get_series(self):
        return Series.objects.filter(journal = self.pk)

class Series(models.Model):
    journal = models.ForeignKey(Journal, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Наименование серии', max_length=128)
    description = models.TextField(verbose_name='О серии', blank=True)
    objects = models.Manager()
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:series-detail', kwargs={'pk': self.pk})

    def get_issues(self):
        return Issue.objects.filter(series = self.pk)
    

class Issue(models.Model):
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    number = models.IntegerField(verbose_name='Номер выпуска', blank=True)
    year = models.IntegerField(verbose_name='Год выпуска', blank=True)
    publication_date = models.DateField(verbose_name='Дата публикации ГГГГ-ММ-ДД', default=timezone.now, blank=True, null=True)
    objects = models.Manager()
    
    def __str__(self):
        return f'{self.year}/{self.number}'

    def get_absolute_url(self):
        return reverse('main:issue-detail', kwargs={'pk': self.pk})
    
    def get_articles(self):
        return Article.objects.filter(issue = self.pk)

class Article(models.Model):
    CREATED = 'CRE'
    REVIEWED = 'REV'
    EDITED = 'EDT'
    INCLUDED = 'INC'
    CANCEL = 'CNC'

    ARTICLE_STATUS_CHOICES = (
        (CREATED, 'создана' ),
        (REVIEWED, 'рецензирована' ),
        (EDITED, 'отредактирована' ),
        (INCLUDED, 'включена в выпуск' ),
        (CANCEL, 'отклонена' ),
    )
    name = models.CharField(verbose_name='Название статьи', max_length=128)
    authors = models.CharField(verbose_name='Авторы', max_length=256, blank=True)
    high_school = models.CharField(verbose_name='Учебные заведения', max_length=256, blank=True)
    description_ru = models.TextField(verbose_name='Краткое описание', blank=True)
    description_en = models.TextField(verbose_name='Short description', blank=True)
    abstract_ru = models.TextField(verbose_name='Аннотация', blank=True)
    abstract_en = models.TextField(verbose_name='Abstract', blank=True)
    keywords = models.CharField(verbose_name='Ключевые слава', max_length=256, blank=True)
    pdf_file = models.FileField(verbose_name='Файл статьи', upload_to='uploads/%Y/%m/%d/', blank=True)
    creation_date = models.DateField(verbose_name='Дата создания', blank=True, default=timezone.now)
    reviewed_date = models.DateField(verbose_name='Дата рецензирования', blank=True, null=True)
    include_date = models.DateField(verbose_name='Дата включения в выпуск', blank=True, null=True)
    status = models.CharField(verbose_name='Cтатус', max_length=3, choices=ARTICLE_STATUS_CHOICES, default=CREATED)
    issue = models.ForeignKey(Issue, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    objects = models.Manager()
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:article-detail', kwargs={'pk': self.pk})

mainapp/forms.py
from django import forms

from mainapp.models import Series, Issue, Article


class SeriesModelForm(forms.ModelForm):
    class Meta:
        model = Series
        fields =[
            'name', 
            # 'journal', 
            'description'
        ]

class IssueModelForm(forms.ModelForm):
    #publication_date = forms.DateField()
    class Meta:
        model = Issue
        fields =[
            'number', 
            # 'series', 
            'year',
            'publication_date'
        ]

class ArticleModelForm(forms.ModelForm):
    class Meta:
        model = Article
        fields =[
            'name', 
            'authors', 
            'high_school', 
            'description_ru', 
            'description_en', 
            'abstract_ru',
            'abstract_en', 
            'keywords', 
            'pdf_file', 
            'creation_date',
            'reviewed_date',
            'include_date',
            'status',
            'issue'
        ]

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from mainapp.models import (
    Journal,
    Series,
    Issue,
    Article
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from mainapp.forms import (
    SeriesModelForm, 
    IssueModelForm,
    ArticleModelForm
)


# Create your views here.

def home(request):
    context = {
        'object': Journal.objects.all()
    }
    return render(request, 'mainapp/home.html', context)

def about(request):
    return render(request, 'mainapp/about.html', {'title': 'About'})

################################# Journal #################################
class JournalListView(ListView):
    model = Journal
    context_object_name = 'object'
    template_name = 'mainapp/home.html'  # <app>/<model>_<viewtype>.html

def journal_detail_view(request, pk):
    obj = get_object_or_404(Journal, id=pk)
    context = {
        'object': obj
    }
    return render(request, 'mainapp/journal_detail.html', context)

class JournalDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Journal
    success_url = '/'

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Journal, id=id_)

    def test_func(self):
        #journal = self.get_object()
        #if self.request.user == post.author: # Задел для разграничения прав доступа
        if self.request.user.is_superuser:
            return True
        return False

class JournalCreateView(LoginRequiredMixin, CreateView):
    model = Journal
    fields = [
        'name', 
        'issn', 
        'description', 
        'rkn_certificate_scan', 
        'redactor', 
        'issue_period', 
        'issuer', 
        'email', 
        'phone', 
        'address'
    ]

    def form_valid(self, form):
        # form.instance.author = self.request.user # Задел для разграничения прав доступа
        return super().form_valid(form)

class JournalUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Journal
    fields = [
        'name', 
        'issn', 
        'description', 
        'rkn_certificate_scan', 
        'redactor', 
        'issue_period', 
        'issuer', 
        'email', 
        'phone', 
        'address'
    ]

    def form_valid(self, form):
        # form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        #obj = self.get_object()
        #if self.request.user == post.author:
        if self.request.user.is_superuser:
            return True
        return False

################################# Series #################################
# Потом переделаю на класс
def series_create_view(request, pk):
    journal = get_object_or_404(Journal, id=pk)
    form = SeriesModelForm()
    if request.method == "POST":
        form = SeriesModelForm(request.POST)
        form.instance.journal = journal
        if form.is_valid():
            form.save()
            form = SeriesModelForm()
    context = {
        'object': journal,
        'form': form
    }
    return render(request, 'mainapp/series_form.html', context)

class SeriesUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Series
    fields = [
        'name', 
        'description', 
    ]

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        return False

class SeriesDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Series
    success_url = '/'

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Series, id=id_)

    def test_func(self):
        #journal = self.get_object()
        #if self.request.user == post.author: # Задел для разграничения прав доступа
        if self.request.user.is_superuser:
            return True
        return False

def series_update_view(request, pk):
    journal = get_object_or_404(Journal, id=pk)
    form = SeriesModelForm()
    if request.method == "POST":
        form = SeriesModelForm(request.POST)
        form.instance.journal = journal
        if form.is_valid():
            form.save()
            form = SeriesModelForm()
    context = {
        'object': journal,
        'form': form
    }
    return render(request, 'mainapp/series_form.html', context)

class SeriesCreateView(LoginRequiredMixin, CreateView):
    model = Series
    fields = [
        'journal', 
        'name', 
        'description'
    ]


def series_detail_view(request, pk):
    obj = get_object_or_404(Series, id=pk)
    context = {
        'object': obj
    }
    return render(request, 'mainapp/series_detail.html', context)

################################# Issue #################################
def issue_detail_view(request, pk):
    obj = get_object_or_404(Issue, id=pk)
    context = {
        'object': obj
    }
    return render(request, 'mainapp/issue_detail.html', context)

def issue_create_view(request, pk):
    series = get_object_or_404(Series, id=pk)
    form = IssueModelForm()
    if request.method == "POST":
        form = IssueModelForm(request.POST)
        form.instance.series = series
        if form.is_valid():
            form.save()
            form = IssueModelForm()
    context = {
        'object': series,
        'form': form
    }
    return render(request, 'mainapp/issue_form.html', context)

class IssueUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Issue
    
    fields = [
        'number', 
        'series', 
        'year',
        'publication_date' 
    ]

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        return False

class IssueDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Issue
    success_url = '/'

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Issue, id=id_)

    def test_func(self):
        #journal = self.get_object()
        #if self.request.user == post.author: # Задел для разграничения прав доступа
        if self.request.user.is_superuser:
            return True
        return False    

################################# Article #################################
def article_detail_view(request, pk):
    obj = get_object_or_404(Article, id=pk)
    context = {
        'object': obj
    }
    return render(request, 'mainapp/article_detail.html', context)

def article_list_view(request):
    if request.user.is_superuser:
        objects = Article.objects.all()
    else:
        objects = Article.objects.filter(user=request.user)   
    context = {
        'object_list': objects
    }
    return render(request, 'mainapp/article_list.html', context)

def article_create_view(request, pk=None):
    if request.method == "GET":
        if pk == None:
            form = ArticleModelForm()
        else:
            issue = get_object_or_404(Issue, id=pk)
            form = ArticleModelForm(initial={'issue':issue})
    if request.method == "POST":
        form = ArticleModelForm(request.POST)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            form = IssueModelForm()
    context = {
        'form': form
    }
    return render(request, 'mainapp/issue_form.html', context)

class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    
    fields = [
        'authors', 
        'high_school', 
        'description_ru', 
        'description_en', 
        'abstract_ru',
        'abstract_en', 
        'keywords', 
        'pdf_file', 
        'creation_date',
        'reviewed_date',
        'include_date',
        'status',
        'issue' 
    ]

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Article, id=id_)

    def test_func(self):
        article = self.get_object()
        if self.request.user.is_superuser or self.request.user == article.user: # Задел для разграничения прав доступа
            return True
        return False

class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    success_url = '/'

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Article, id=id_)

    def test_func(self):
        article = self.get_object()
        if self.request.user.is_superuser or self.request.user == article.user: 
            return True
        return False    

mainapp/templates/mainapp/about.html
{% extends "mainapp/base.html" %}
{% block content %}
    <h1>Контакты</h1>
{% endblock content %}

mainapp/templates/mainapp/article_confirm_delete.html
{% extends "mainapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Удаление журнала</legend>
                {{ form|crispy }}
                <h2>Уверены что хотите удалить журнал {{ object.name }}?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Удалить</button>
                <a class="btn btn-outline-secondary" href="{% url 'main:article-detail' object.id %}">Отмена</a>
            </div>
        </form>
    </div>
{% endblock content %}

mainapp/templates/mainapp/article_detail.html
{% extends "mainapp/base.html" %}
{% block content %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ object.issn }}</a>
              <small class="text-muted"> </small>
              {% if user.is_superuser %}
                <div>
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'main:article-update' object.id  %}">Изменить</a>
                  <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'main:article-delete' object.id  %}">Удалить</a>
                </div>
              {% endif %}
            </div>
            <h2 class="article-title">{{ object.name }}</h2>
            <p class="article-content">Авторы: {{ object.authors }}</p> 
            <p class="article-content">Учебные заведения: {{ object.high_school }}</p> 
            <p class="article-content">Краткое описание: {{ object.description_ru }}</p> 
            <p class="article-content">Description: {{ object.description_en }}</p> 
            <p class="article-content">Аннотация: {{ object.abstract_ru }}</p> 
            <p class="article-content">Abstract: {{ object.abstract_en }}</p> 
            <p class="article-content">Ключевые слава: {{ object.keywords }}</p> 
            <p class="article-content">Дата создания: {{ object.creation_date }}</p> 
            <p class="article-content">Дата рецензирования: {{ object.reviewed_date }}</p> 
            <p class="article-content">Дата включения в выпуск: {{ object.include_date }}</p> 
            <p class="article-content">Cтатус: {{ object.status }}</p> 
            <a class="article-content" target="_blank" href="{{ object.pdf_file.url }}">Файл статьи</a> 
          </div>
        </article>
{% endblock content %}

mainapp/templates/mainapp/article_form.html
{% extends "mainapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Создание статьи</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock content %}

mainapp/templates/mainapp/article_list.html
{% extends "mainapp/base.html" %}
{% block content %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#"></a>
              <small class="text-muted"> </small>
              
            </div>
            <h5 class="article-title">Статьи:</h5>
            {% for article in object_list %} 
            <h6><a class="article-title" href="{% url 'main:article-detail' article.id  %}">
                {{ article }}
                {% if article.issue %}
                Выпуск {{ article.issue }} ({{article.issue.series}},{{article.issue.series.journal}})
                {% endif %}
            </a></h6>
            {% endfor %} 
            {% if user.is_superuser %}
              <small class="text-muted"><a class="article-title" href="{% url 'main:article-create' %}">Добавить статью</a> </small>
            {% endif %}
          </div>
        </article>
{% endblock content %}

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    
    
    <title>Хостинг журналов</title>
    
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'main:home' %}">Хостинг журналов</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'main:home' %}">Главная</a>
              <a class="nav-item nav-link" href="{% url 'main:about' %}">Контакты</a>
            </div>
            <form class="form-inline my-2" action= "{% url 'main:home' %}">
              <input class="form-control" type="search" placeholder="Введите ключевые слова" name="search" aria-label="search">
              <button class="btn btn-outline-light ml-1" type="submit">Поиск</button>
            </form>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                {% if user.is_superuser %}
                  <a class="nav-item nav-link" href="/admin">Админка</a>
                  <a class="nav-item nav-link" href="{% url 'main:article-list' %}">Статьи</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'main:article-list' %}">Мои статьи</a>
                {% endif %}
              <a class="nav-item nav-link" href="{% url 'profile' %}">Профиль</a>
              <a class="nav-item nav-link" href="{% url 'logout' %}">Выход</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'login' %}">Вход</a>
              <a class="nav-item nav-link" href="{% url 'register' %}">Регистрация</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Issues</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

mainapp/templates/mainapp/issue_detail.html
{% extends "mainapp/base.html" %}
{% block content %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ object.issn }}</a>
              <small class="text-muted"> </small>
              {% if user.is_superuser %}
                <div>
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'main:issue-update' object.id  %}">Изменить</a>
                  <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'main:issue-delete' object.id  %}">Удалить</a>
                </div>
              {% endif %}
            </div>
            <h2 class="article-title">Выпуск {{ object }} ({{ object.series }}, {{ object.series.journal }})</h2>
            <h5 class="article-title">Статьи:</h5>
            {% for article in object.get_articles %} 
            <h6><a class="article-title" href="{% url 'main:article-detail' object.id  %}">{{ article }}</a></h6>
            {% endfor %} 
            {% if user.is_superuser %}
              <small class="text-muted"><a class="article-title" href="{% url 'main:article-issue-create' object.id %}">Добавить статью</a> </small>
            {% endif %}
          </div>
        </article>
{% endblock content %}

mainapp/templates/mainapp/journal_detail.html
{% extends "mainapp/base.html" %}
{% block content %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ object.issn }}</a>
              <small class="text-muted"> </small>
              {% if user.is_superuser %}
                <div>
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'main:journal-update' object.id %}">Изменить</a>
                  <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'main:journal-delete' object.id %}">Удалить</a>
                </div>
              {% endif %}
            </div>
            <h2 class="article-title">{{ object.name }}</h2>
            <p class="article-content">Описание: {{ object.description|linebreaks }}</p>
            <p class="article-content">Редактор: {{ object.redactor }}</p>
            <p class="article-content">Периодичность: {{ object.issue_period }}</p>
            <p class="article-content">Издательство: {{ object.issuer }}</p>
            <p class="article-content">Адрес электронной почты: {{ object.email }}</p>
            <p class="article-content">Телефон: {{ object.phone }}</p>
            <p class="article-content">Почтовый адрес: {{ object.address }}</p>
            <h5 class="article-title">Серии журнала:</h5>
            {% for ser in object.get_series %} 
            <h6><a class="article-title" href="{% url 'main:series-detail' ser.pk %}">{{ ser.name }}</a></h6>
            <p class="article-content">{{ ser.description }}</p>
            {% endfor %} 
            {% if user.is_superuser %}
              <small class="text-muted"><a class="article-title" href="{% url 'main:series-create' object.id %}">Добавить серию</a> </small>
            {% endif %}
          </div>
        </article>
{% endblock content %}